### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by r-bt** [NoahVersace/svelte-notion#3]
Hey,

I made this logo for a fork of [@leveluptuts/svelte-notion](https://github.com/leveluptuts/svelte-notion) I had but this package is much better, so if you want it you're free to use it :)

![notion-in-svelte](https://user-images.githubusercontent.com/2939329/108627599-6a064900-744e-11eb-817e-8cd5a4aea3f0.png)

**Comment by noahsalvi** [comment]
I really appreciate it, thanks

FYI I'll be working on svelte-notion again since my other project that I was working on is almost finished 👍
